import { expandBraces } from "./match.js";
import type { Policy, Rule } from "./policy.js";

export interface CodexExport {
  text: string;
  exported: { rule: string; pattern: string }[];
  skipped: { rule: string; pattern?: string; why: string }[];
}

const starlark = (s: string) => JSON.stringify(s);

/**
 * Translate agent-fence command rules into Codex exec-policy `prefix_rule`s.
 * Codex rules match argv prefixes in order, so only patterns made of literal
 * words (and {a,b} alternatives) translate, and they match more narrowly than
 * agent-fence does (flags must be in the written position). deny becomes
 * "forbidden", ask becomes "prompt"; allow rules are not exported because
 * agent-fence never grants permission.
 */
export function exportCodexRules(policy: Policy): CodexExport {
  const exported: CodexExport["exported"] = [];
  const skipped: CodexExport["skipped"] = [];
  const lines = [
    "# Generated by agent-fence (codex-rules). Do not edit; regenerate instead.",
    `# Source project: ${policy.root}`,
    "",
  ];
  const consider = (r: Rule) => {
    if (r.action === "allow") return skipped.push({ rule: r.id, why: "allow rules are not exported" });
    if (!r.commands) return skipped.push({ rule: r.id, why: "only command patterns translate to Codex rules" });
    if (r.pipedInput) return skipped.push({ rule: r.id, why: "piped_input has no Codex equivalent" });
    for (const p of r.commands) {
      const words = p.source.trim().split(/\s+/);
      if (words.some((w) => /[*?\\]/.test(w))) {
        skipped.push({ rule: r.id, pattern: p.source, why: "wildcards have no Codex equivalent" });
        continue;
      }
      const parts = words.map((w) => {
        const alts = expandBraces(w);
        return alts.length === 1 ? starlark(alts[0]) : `[${alts.map(starlark).join(", ")}]`;
      });
      lines.push(
        `prefix_rule(pattern=[${parts.join(", ")}], decision=${starlark(r.action === "deny" ? "forbidden" : "prompt")}, justification=${starlark(`agent-fence ${r.id}: ${r.reason}`)})`,
      );
      exported.push({ rule: r.id, pattern: p.source });
    }
  };
  for (const r of policy.rules) if (r.tools.includes("bash")) consider(r);
  return { text: lines.join("\n") + "\n", exported, skipped };
}
